# Generated by Django 5.2.3 on 2025-07-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('Vacation Leave', 'Vacation'), ('Sick Leave', 'Sick'), ('Paternity Leave', 'Paternity'), ('Maternity Leave', 'Maternity')], max_length=100)),
                ('leave_description', models.CharField(max_length=255)),
                ('leave_status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField()),
                ('overtime_start_time', models.TimeField()),
                ('overtime_end_time', models.TimeField()),
                ('overtime_description', models.CharField(max_length=255)),
                ('overtime_status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('Halfday', 'Halfday'), ('Temporary Shift', 'Temp Shift')], max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('shift_status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
            ],
        ),
    ]
