# Generated by Django 5.2.3 on 2025-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_type', models.CharField(max_length=100)),
                ('leave_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('end_start', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
