# Generated by Django 5.2.3 on 2025-06-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_event', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='employees',
            field=models.ManyToManyField(related_name='calendar_events', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_requests', to='employee.employee'),
        ),
    ]
