# Generated by Django 5.2.3 on 2025-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftchangerequest',
            name='shift_type',
            field=models.CharField(choices=[('Halfday', 'Halfday'), ('Temporary Shift', 'Temp Shift')], max_length=100),
        ),
    ]
