# Generated by Django 5.2.3 on 2025-07-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_leave_paid',
            field=models.BooleanField(default=False),
        ),
    ]
