# Generated by Django 5.2.3 on 2025-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0003_alter_shiftchangerequest_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='shift_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Vacation Leave', 'Vacation'), ('Sick Leave', 'Sick'), ('Paternity Leave', 'Paternity'), ('Maternity Leave', 'Maternity')], max_length=100),
        ),
    ]
