# Generated by Django 5.2.3 on 2025-06-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0004_leave_leave_status_shiftchangerequest_shift_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftchangerequest',
            old_name='end_start',
            new_name='break_end',
        ),
    ]
