# Generated by Django 5.2.3 on 2025-07-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_event', '0005_rename_end_start_shiftchangerequest_break_end'),
        ('employee', '0006_employee_total_duty_hrs_employee_total_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_start_time', models.TimeField()),
                ('overtime_end_time', models.TimeField()),
                ('overtime_description', models.CharField(max_length=255)),
                ('overtime_status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='employee.employee')),
            ],
        ),
    ]
