# Generated by Django 5.2.3 on 2025-06-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='end_start',
            new_name='break_end',
        ),
    ]
