# Generated by Django 5.2.3 on 2025-06-26 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days',
            field=models.ManyToManyField(related_name='employees_working', to='employee.dayofweek'),
        ),
        migrations.AddField(
            model_name='employee',
            name='incentives',
            field=models.ManyToManyField(blank=True, related_name='employee_incentives', to='employee.incentive'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employee.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_position', to='employee.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.shift'),
        ),
    ]
