# Generated by Django 5.2.3 on 2025-06-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_end_start_shift_break_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
