# Generated by Django 5.2.3 on 2025-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_leave', models.IntegerField(default=10)),
                ('sick_leave', models.IntegerField(default=10)),
            ],
        ),
    ]
