# Generated by Django 5.2.3 on 2025-06-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.png', null=True, upload_to='avatar/'),
        ),
    ]
