# Generated by Django 5.2.3 on 2025-07-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_totalleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalleave',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_leave', to='employee.employee'),
        ),
    ]
