# Generated by Django 5.2.3 on 2025-07-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('work', 'Work Days'), ('on_call', 'On Call Days'), ('rest', 'Rest Day')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
