# Generated by Django 5.2.3 on 2025-06-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_avatar_employee_educational_attainment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='career_status',
        ),
    ]
