# Generated by Django 5.2.3 on 2025-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_totalleave_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to='avatar/'),
        ),
    ]
