# Generated by Django 5.2.3 on 2025-07-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeedaytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeYearlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('work', 'Work Days'), ('on_call', 'On Call Days'), ('rest', 'Rest Day')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_schedules', to='employee.employee')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='EmployeeDayType',
        ),
    ]
