# Generated by Django 5.2.3 on 2025-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeyearlyschedule_delete_employeedaytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_duty_hrs',
            field=models.CharField(default='8', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_working_days',
            field=models.CharField(default='22', max_length=100),
        ),
    ]
