# Generated by Django 5.2.3 on 2025-07-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_documentprocessing'),
        ('employee', '0005_alter_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentive',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incentive', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='company.company'),
            preserve_default=False,
        ),
    ]
