# Generated by Django 5.2.3 on 2025-07-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_department_company_incentive_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='company',
        ),
    ]
