# Generated by Django 5.2.3 on 2025-07-30 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_documentprocessing'),
        ('employee', '0007_remove_position_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalleave',
            name='employee',
        ),
        migrations.AddField(
            model_name='totalleave',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='total_leave', to='company.company'),
            preserve_default=False,
        ),
    ]
