# Generated by Django 5.2.3 on 2025-07-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_documentprocessing'),
        ('employee', '0009_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department_name', 'company')},
        ),
    ]
