# Generated by Django 5.2.3 on 2025-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_pagibigcontributionrule_philhealthcontributionrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssscontribution',
            name='employee_regular_ss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ssscontribution',
            name='employer_ec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ssscontribution',
            name='employer_regular_ss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ssscontribution',
            name='regular_ss_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
