# Generated by Django 5.2.3 on 2025-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_ssscontribution_employee_regular_ss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philhealthcontributionrule',
            name='employee_rate',
            field=models.DecimalField(decimal_places=3, help_text='Percentage rate (e.g. 1.00 or 2.00)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='philhealthcontributionrule',
            name='employer_rate',
            field=models.DecimalField(decimal_places=3, help_text='Percentage rate (e.g. 2.00)', max_digits=4),
        ),
    ]
