# Generated by Django 5.2.3 on 2025-07-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_philhealthcontributionrule_employee_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withholdingtaxbracket',
            options={},
        ),
        migrations.AddField(
            model_name='computepay',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computepay',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computepay',
            name='total_sss_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollgenerate',
            name='deduction_type',
            field=models.CharField(choices=[('No Deduction', 'No Deduction'), ('Per Cut-Off', 'Per Cut Off'), ('Second Cut-Off', 'Second Cut Off')], default='No Deduction', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollgenerate',
            name='first_cut_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollgenerate',
            name='second_cut_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computepay',
            name='total_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='computepay',
            name='total_gross_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='computepay',
            name='total_late_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='computepay',
            name='total_net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='computepay',
            name='total_overtime_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='computepay',
            name='total_undertime_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagibigcontributionrule',
            name='employee_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pagibigcontributionrule',
            name='employer_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='philhealthcontributionrule',
            name='employee_rate',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='philhealthcontributionrule',
            name='employer_rate',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
