# Generated by Django 5.2.3 on 2025-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_withholdingtaxbracket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computepay',
            name='total_pagibig_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='computepay',
            name='total_philhealth_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='computepay',
            name='total_tax_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
