# Generated by Django 5.2.3 on 2025-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('total_hours_worked', models.CharField(default='8', max_length=10)),
                ('late', models.CharField(max_length=10)),
                ('undertime', models.CharField(max_length=10)),
                ('overtime', models.JSONField(blank=True, default=dict)),
                ('holiday_types', models.JSONField(blank=True, default=list)),
                ('night_diff_hours', models.JSONField(blank=True, default=dict)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
