# Generated by Django 5.2.3 on 2025-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('late', models.CharField(max_length=10)),
                ('undertime', models.CharField(max_length=10)),
                ('overtime', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
