# Generated by Django 5.2.3 on 2025-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours_worked',
            field=models.CharField(default='8', max_length=10),
        ),
    ]
