# Generated by Django 5.2.3 on 2025-07-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_rest_day',
            field=models.BooleanField(default=False),
        ),
    ]
