# Generated by Django 5.2.3 on 2025-07-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_night_shift',
            new_name='is_halfday',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_leave_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_oncall',
            field=models.BooleanField(default=False),
        ),
    ]
