# Generated by Django 5.2.3 on 2025-07-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamping_image', models.ImageField(upload_to='stamping_images/')),
            ],
        ),
    ]
