import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ReactQueryProvider from "./components/ReactQueryProvider";
import '@ant-design/v5-patch-for-react-19';
import "./globals.css";

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crimson System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AntdRegistry>
            <ConfigProvider
              theme={{
                components: {
                  Table: {
                    headerBg: '#001529',
                    headerColor: 'white',
                    fontSize: 12
                  },
                },
              }}
            >
              {children}
            </ConfigProvider>
          </AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
